DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS TV;
DROP TABLE IF EXISTS Comics;

CREATE TABLE Comics (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    tag VARCHAR(100) NOT NULL
);

CREATE TABLE TV (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    tag VARCHAR(100) NOT NULL
);

CREATE TABLE Movies (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL
);
